---
- name: install MySQL Exporter
  become: yes
  apt:
    name: prometheus-mysqld-exporter

- name: Config
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify: Restart MySQL Exporter

- name: MySQL Exporter user
  mysql_user:
    name: "ryo"
    password: "{{ mysql_exporter_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:PROCESS,REPLICATIONS CLIENT,SELECT"
  no_log: True

- name: Enabled
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes